### ISSUE TITLE
mnemonic to account test vector

### ISSUE THREAD

**Issue by tim-eucalyptus** [obsidiansystems/ledger-app-kadena#32]
I'm creating a kadena wallet, and I want it to be one-to-one compatible with this Kadena-Ledger wallet when they both are released to the public. 

Could you do me a big favor and tell me what "K-address" is generated for this 24-word mnemonic phrase using the ledger kana app that you are working on here?:

```
chair kick cage analyst afraid inch celery journey test eagle excite garbage uncle tennis heavy carry rent seven degree gesture tumble ensure tissue bread
```

**Comment by dfordivam** [comment]
@tim-eucalyptus I used the speculos to obtain the public key

`cargo run --target=nanosplus.json -- --display headless -s 'chair kick cage analyst afraid inch celery journey test eagle excite garbage uncle tennis heavy carry rent seven degree gesture tumble ensure tissue bread'`

Result -> `ea49bbfac26ce5d5c8e71c2d10053c8bbddf0e1f42398b4fc2a1d8281658fd5c`

**Comment by tim-eucalyptus** [comment]
Does that also use the derivation path: "44'/626'/0'/0/0"?

**Comment by dfordivam** [comment]
Yes,  "44'/626'/0'/0/0"
